export interface Product {
  id: string;
  name: string;
  description: string;
  price: number;
  category: 'Kimono' | 'Equipamento' | 'Faixa' | 'Acessório';
  image: string;
  rating: number;
  reviewCount: number;
  inStock: boolean;
  badge?: 'Novo' | 'Mais Vendido' | 'Promoção';
  originalPrice?: number;
}

export const mockProducts: Product[] = [
  {
    id: '1',
    name: 'Kimono Shureido WKF Approved',
    description: 'Kimono de competição aprovado pela WKF, tecido premium 100% algodão japonês.',
    price: 349.90,
    category: 'Kimono',
    image: 'https://loremflickr.com/400/300/karate,kimono?lock=1',
    rating: 5,
    reviewCount: 42,
    inStock: true,
    badge: 'Mais Vendido',
  },
  {
    id: '2',
    name: 'Kimono Tokaido Kata Master',
    description: 'Kimono leve e resistente, ideal para treinos de kata de alto nível.',
    price: 289.90,
    category: 'Kimono',
    image: 'https://loremflickr.com/400/300/karate,uniform?lock=2',
    rating: 4,
    reviewCount: 28,
    inStock: true,
  },
  {
    id: '3',
    name: 'Kimono Infantil Iniciante',
    description: 'Kimono confortável para crianças iniciantes, tecido durável e fácil de lavar.',
    price: 119.90,
    category: 'Kimono',
    image: 'https://loremflickr.com/400/300/karate,children?lock=3',
    rating: 4,
    reviewCount: 65,
    inStock: true,
  },
  {
    id: '4',
    name: 'Protetor de Mão WKF',
    description: 'Luvas de competição aprovadas pela WKF, espuma de alta densidade.',
    price: 89.90,
    category: 'Equipamento',
    image: 'https://loremflickr.com/400/300/boxing,gloves?lock=4',
    rating: 5,
    reviewCount: 31,
    inStock: true,
    badge: 'Novo',
  },
  {
    id: '5',
    name: 'Caneleira + Protetor de Pé',
    description: 'Kit caneleira com protetor de pé homologado para kumite.',
    price: 129.90,
    category: 'Equipamento',
    image: 'https://loremflickr.com/400/300/shin,guards,sports?lock=5',
    rating: 4,
    reviewCount: 19,
    inStock: true,
  },
  {
    id: '6',
    name: 'Protetor de Cabeça Adulto',
    description: 'Protetor de cabeça WKF para competição, ajuste por velcro.',
    price: 159.90,
    originalPrice: 199.90,
    category: 'Equipamento',
    image: 'https://loremflickr.com/400/300/helmet,protective,sport?lock=6',
    rating: 4,
    reviewCount: 12,
    inStock: true,
    badge: 'Promoção',
  },
  {
    id: '7',
    name: 'Protetor Bucal',
    description: 'Protetor bucal moldável, absorção de impacto superior.',
    price: 29.90,
    category: 'Equipamento',
    image: 'https://loremflickr.com/400/300/mouthguard,sport?lock=7',
    rating: 3,
    reviewCount: 8,
    inStock: true,
  },
  {
    id: '8',
    name: 'Faixa Preta Dan - Seda',
    description: 'Faixa preta em seda bordada com nome e graduação a escolher.',
    price: 79.90,
    category: 'Faixa',
    image: 'https://loremflickr.com/400/300/karate,belt,black?lock=8',
    rating: 5,
    reviewCount: 54,
    inStock: true,
    badge: 'Mais Vendido',
  },
  {
    id: '9',
    name: 'Kit Faixas Coloridas Infantil',
    description: 'Kit com 6 faixas coloridas para criança, branca ao marrom.',
    price: 59.90,
    category: 'Faixa',
    image: 'https://loremflickr.com/400/300/martial,belt,colorful?lock=9',
    rating: 4,
    reviewCount: 37,
    inStock: true,
  },
  {
    id: '10',
    name: 'Faixa Preta Algodão Standard',
    description: 'Faixa preta resistente em algodão, ótimo custo-benefício.',
    price: 39.90,
    category: 'Faixa',
    image: 'https://loremflickr.com/400/300/karate,belt?lock=10',
    rating: 4,
    reviewCount: 22,
    inStock: true,
  },
  {
    id: '11',
    name: 'Bolsa de Equipamentos Karate',
    description: 'Bolsa esportiva com compartimento para kimono e acessórios, 50L.',
    price: 149.90,
    originalPrice: 179.90,
    category: 'Acessório',
    image: 'https://loremflickr.com/400/300/sports,bag,gym?lock=11',
    rating: 5,
    reviewCount: 16,
    inStock: true,
    badge: 'Promoção',
  },
  {
    id: '12',
    name: 'Adesivo de Kata — Diagrama',
    description: 'Poster plastificado com diagrama dos principais katas Shotokan.',
    price: 24.90,
    category: 'Acessório',
    image: 'https://loremflickr.com/400/300/karate,poster,training?lock=12',
    rating: 4,
    reviewCount: 9,
    inStock: false,
  },
  {
    id: '13',
    name: 'Timer Eletrônico de Combate',
    description: 'Cronômetro digital para treinos de kumite, alarme com sonoridade forte.',
    price: 199.90,
    category: 'Acessório',
    image: 'https://loremflickr.com/400/300/stopwatch,timer,sport?lock=13',
    rating: 5,
    reviewCount: 7,
    inStock: true,
    badge: 'Novo',
  },
];
